// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Pijze.Infrastructure.Data.EntityFramework.Migrations
{
    [DbContext(typeof(PijzeDbContext))]
    partial class PijzeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Pijze.Domain.Beers.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("Pijze.Domain.Beers.Beer", b =>
                {
                    b.OwnsOne("Pijze.Domain.Beers.BeerImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("BeerId")
                                .HasColumnType("TEXT");

                            b1.Property<byte[]>("Bytes")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Image");

                            b1.HasKey("BeerId");

                            b1.ToTable("Beers");

                            b1.WithOwner()
                                .HasForeignKey("BeerId");
                        });

                    b.Navigation("Image")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
