name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push PijzeBff Docker Image
      run: |
        docker build -t karol93/pijze-bff:latest -f ./Bff/Pijze.Bff/Dockerfile .
        docker push karol93/pijze-bff:latest

    - name: Build and Push PijzeApi Docker Image
      run: |
        docker build -t karol93/pijze-api:latest -f ./Api/src/Pijze.Api/Dockerfile .
        docker push karol93/pijze-api:latest
